// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCys_AN6hwOx16V9aj7XSkQ-JzYRX35yp0',
    appId: '1:26173660557:android:34f0696af84695cb4631c4',
    messagingSenderId: '26173660557',
    projectId: 'finalapp-373ef',
    storageBucket: 'finalapp-373ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBApQm0kQeEtCDCUUp8ab51WA7nZUtzSOQ',
    appId: '1:26173660557:ios:1b34f8ba26b7b1cd4631c4',
    messagingSenderId: '26173660557',
    projectId: 'finalapp-373ef',
    storageBucket: 'finalapp-373ef.appspot.com',
    iosBundleId: 'com.example.myappfinal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzwRIWRK6RibrcLPVVCwOM-GwyyIlj8uw',
    appId: '1:26173660557:web:ede7a65b60a734d94631c4',
    messagingSenderId: '26173660557',
    projectId: 'finalapp-373ef',
    authDomain: 'finalapp-373ef.firebaseapp.com',
    storageBucket: 'finalapp-373ef.appspot.com',
    measurementId: 'G-MQQN93176Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBApQm0kQeEtCDCUUp8ab51WA7nZUtzSOQ',
    appId: '1:26173660557:ios:1b34f8ba26b7b1cd4631c4',
    messagingSenderId: '26173660557',
    projectId: 'finalapp-373ef',
    storageBucket: 'finalapp-373ef.appspot.com',
    iosBundleId: 'com.example.myappfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzwRIWRK6RibrcLPVVCwOM-GwyyIlj8uw',
    appId: '1:26173660557:web:55cca729b0c006c94631c4',
    messagingSenderId: '26173660557',
    projectId: 'finalapp-373ef',
    authDomain: 'finalapp-373ef.firebaseapp.com',
    storageBucket: 'finalapp-373ef.appspot.com',
    measurementId: 'G-413LBE05GW',
  );

}